### ISSUE TITLE
Add mobile meta tag

### ISSUE THREAD

**Issue by amyhenning** [oOCrystalOo/ruby-splurty#1]
Hey Crystal, 

Great job with your Splurty app!

Things look great with the Bootstrap styles and fonts you added - but on mobile things don't look as good as they could be. This is a common issue with a pretty simple fix.

Google search for how you can add a "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile. Once you find a tag to add, you can add it to your `application.html.erb` file here:

https://github.com/oOCrystalOo/ruby-splurty/blob/master/app/views/layouts/application.html.erb#L7

Let me know in the comments once you figured that step out :)

Keep up the good work!

--Amy

**Comment by oOCrystalOo** [comment]
Hi Amy,

I've updated my code with the meta tag (or at least, what I _think_ is the meta tag), but when I refresh my page, I haven't noticed any difference. I've tried both resizing my browser manually, as well as using Chrome's mobile view emulator. 

Please let me know if I've added the correct tag, or if I should do another round of Google search :)

Thanks,
Crystal

**Comment by amyhenning** [comment]
Hi Crystal,

That looks like the right tag to me! Did you push your changes to Heroku after pushing up to Github?

Thanks,

Amy

**Comment by oOCrystalOo** [comment]
Hi Amy,

Yes I did. I've also tried re-pushing just in case, but everything is up to date.

Thanks,
Crystal

**Comment by amyhenning** [comment]
Interesting. This tag from MDN (slightly different from yours) is one I've found useful in the past - maybe give it a shot and see if it works for you.

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by oOCrystalOo** [comment]
Hi Amy,

I've updated my meta tag with the one that you've provided, but I still haven't really noticed any changes. 
I wonder if this is related to the issue that github is warning me about - where the bootstrap version is too low. Should I change it to >= 4.1.2? Currently, I'm using 4.0.0.alpha6, as per the course's instructions.

Crystal

**Comment by amyhenning** [comment]
Hi Crystal,

Thanks so much for checking into this. I just added the same tag to my Splurty app to test things out and it made the design responsive on mobile for me. This isn't a huge deal, so if it's still not working properly you, I wouldn't worry about it too much at this stage. You might want to try adding the mobile meta tag to the app you're currently working on and seeing if it affects your views on mobile.

Thanks,

Amy

**Comment by oOCrystalOo** [comment]
Ok, I'll try it with the nomster app.
I'll close this then, thanks :)
